development:
  program: 'cmo-development'
  root_url: 'localhost:3000'
  access_key: 'AKIAI4VKRSMMQBAFXVSQ'
  access_secret: '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'
  form_action: 'https://online-admissions.s3.amazonaws.com/'
production:
  program: 'cmo'
  root_url: 'cmo-aim.herokuapp.com'
  access_key: 'AKIAI4VKRSMMQBAFXVSQ'
  access_secret: 'RODdfE3mWqLQUf7TrqPoE3hGrd7n8MAKKB5m+nnsk'
  form_action: 'https://online-admissions.s3.amazonaws.com/'