development:
  program: 'mba-development'
  root_url: 'localhost:3000'
  access_key: 'AKIAITSSLQL5NKW2DQQA'
  access_secret: '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'
  form_action: 'https://online-admissions.s3.amazonaws.com/'
production:
  program: 'mba'
  root_url: 'mbaonlineadmissions.aim.edu'
  access_key: 'AKIAITSSLQL5NKW2DQQA'
  access_secret: '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'
  form_action: 'https://online-admissions.s3.amazonaws.com/'