development:
  program: 'cmo-development'
  root_url: 'localhost:3000'
  access_key: 'AKIAJW37VPAF5P25Z6SQ'
  access_secret: 'NHHP1pH9xESpRgr3ua03wlXWf8Dj6amaFbJmzZz2k'
  form_action: 'https://online-admissions.s3.amazonaws.com/'
production:
  program: 'cmo'
  root_url: 'cmo-aim.herokuapp.com'
  access_key: 'AKIAJW37VPAF5P25Z6SQ'
  access_secret: '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'
  form_action: 'https://online-admissions.s3.amazonaws.com/'